### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by davecotter** [railduino/zeroconf-lookup#1]
Sorry, that did not work
Error: Attempt to postMessage on disconnected port

**Comment by railduino** [comment]
Can you please give a little bit more information?
Which browser, which version of the extension, which op-sys?
Right now the entire thing is not yet robust in every possible constellation.

**Comment by davecotter** [comment]
oh, sorry, sure: 
mac
Firefox 58.0.2 (64bit)
plugin v 2.0.0

**Comment by railduino** [comment]
Just to make sure:
Did you install the native messaging host software? Where?
Does the "path" line in the Mozilla manifest point to this path?
Can you invoke "zeroconf_lookup -h" and it returns a help message?
Oh, and did it work before or is this a first-time?
(Sorry for asking more questions .....)

**Comment by railduino** [comment]
Hi, I have added an updated version and (hopefully) better installation instructions at:
https://github.com/railduino/zeroconf-lookup/blob/master/INSTALL.md
Please let me know if it helps.

**Comment by fwenzel** [comment]
No way to install the necessary binaries with the extension?

<img width="431" alt="screenshot 2018-03-04 15 52 48" src="https://user-images.githubusercontent.com/87232/36952400-4df911b6-1fc4-11e8-9bc9-77a427ffc267.png">

**Comment by railduino** [comment]
Not that I know. Both browsers do not allow networking and file system access. Native Messaging is the defined doorway so that browsers cannot do harmful things on their own.

**Comment by davecotter** [comment]
oh. "native messaging host software", no.  i'm looking for a one-click installer.  if it were just me, sure, but the goal here is to send newbie users off to get this installed, and anything other than "click here" just isn't going to fly.  i'll have to find some other solution or give up.

**Comment by railduino** [comment]
Then good luck! I had been searching for such a solution myself before writing this software. The separation of responsibility is part of the design with new browsers. Is it okay if I close the issue?

**Comment by davecotter** [comment]
yes
